"""add experience and level

Revision ID: f1667cd74000
Revises: 1e9ce54fa737
Create Date: 2026-02-27 07:42:38.706971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1667cd74000'
down_revision: Union[str, Sequence[str], None] = '1e9ce54fa737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('characters', sa.Column('experience', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'experience')
    op.drop_column('characters', 'level')
    # ### end Alembic commands ###
