"""add mana

Revision ID: 35a38a75934c
Revises: dc293ac8561f
Create Date: 2026-02-24 21:10:29.693246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a38a75934c'
down_revision: Union[str, Sequence[str], None] = 'dc293ac8561f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('mana', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'mana')
    # ### end Alembic commands ###
