"""add max_health

Revision ID: 5e8019f76e83
Revises: f1667cd74000
Create Date: 2026-02-27 09:33:27.001811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8019f76e83'
down_revision: Union[str, Sequence[str], None] = 'f1667cd74000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('max_health', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'max_health')
    # ### end Alembic commands ###
